### ISSUE TITLE
ejabberd PR

### ISSUE THREAD

**Issue by Neustradamus** [freedominion-org/fdo-server#1]
Hello Euan,

Sorry for this place but after some months, an email, I contact you again here about ejabberd.

Can you look your PR? (PR 2344)
Can you sign the CLA?
Update your code to last ejabberd version?

Thanks in advance.

Regards,

Neustradamus

**Comment by ethoms** [comment]
Closing issue, as not related to this project.

**Comment by Neustradamus** [comment]
Thanks for your comeback in the ejabberd repository :)
